apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: <accsess-key-id-base64>
  AWS_SECRET_ACCESS_KEY: <secret access key base64>
